security:

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: user_provider

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            logout:
                path: app_logout

    access_control:
        - { path: ^/add-stagiaire, roles: ['ROLE_ADMIN'] }